dist: trusty
sudo: required
language: c
os: linux

cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin
  
addons:
  apt:
    sources:
    - avsm
 
env:
  global:
  - NJOBS=2
  - COMPILER="4.07.1"
  matrix:
  - COQ_VER="8.12.0" EQUATIONS_VER="1.2.3+8.12" METACOQ_VER="1.0~beta1+8.12" SMPL_VER="8.12" BASE_VER="1.0.2+8.12" UNDECLIB_VER="dev+8.12"

install:
- curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
- export PATH=$HOME/bin:$PATH
- which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
- opam --version
- opam update
- opam init -j ${NJOBS} -n -y --compiler=$COMPILER
- opam switch set ${COMPILER}
- eval $(opam config env)
- opam config list
- opam repo add coq-released https://coq.inria.fr/opam/released || echo "coq-released registered"
- opam repo add psl-opam-repository https://github.com/uds-psl/psl-opam-repository.git || echo "psl-opam-repository registered"
- opam install -j ${NJOBS} -y coq.${COQ_VER} coq-equations.${EQUATIONS_VER} coq-metacoq-template.${METACOQ_VER} coq-metacoq-checker.${METACOQ_VER} coq-smpl.${SMPL_VER} coq-psl-base-library.${BASE_VER}
- travis_wait 45 opam install -j ${NJOBS} coq-library-undecidability.${UNDECLIB_VER}
- opam list

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: build
      script:
        - make -j ${NJOBS} all
